### ISSUE TITLE
Copying clipboard

### ISSUE THREAD

**Issue by TheYkk** [origin-brain/deepops#139]
1. Go to the https://datav.dev/ 
2. Click copy icon right next to docker command
3. It will copy `npm install tailwind` it should be `docker run -d --name=datav -p 3000:3000 -p 3001:3001 opendatav/datav`

I was wanted to fix but I saw docs folder was removed from repo.

**Comment by sunface** [comment]
Hi, @TheYkk ,  sorry for reply so late.

 Datav website has been removed out of datav main repo, you can access opendatav/datav-website and fix it , thanks for your contributing : )
