### ISSUE TITLE
老鼠出洞03 - 请解释多次瞬间Star徒增的情况

### ISSUE THREAD

**Issue by HIKVisio** [origin-brain/deepops#163]
![image](https://user-images.githubusercontent.com/98039169/150162545-6702c676-5075-4eb2-8b93-898d8717ee06.png)

一个几乎没有社区关注度的项目，为何能在一瞬间获得500以上Star？

请给中国开源社区一个说明，谢谢合作！

**Comment by sunface** [comment]
哦哟，7个小时前注册的小号老鼠又出洞了，一只老鼠有什么本事代表开源社区？你代表老鼠洞差不多，要解释是不？

那我给你个解释，你可以回头去看看那个时候有个对应的issue，是一个github知名项目的创始人和其团队关注了datav，所以连锁反应带来了一连串star。

对了，为了防止大家不知道，这只老鼠，同时黑我好几个项目，还开各种小号黑，具体：

- https://github.com/sunface/rust-course/issues/253
- https://github.com/sunface/rust-course/issues/242

大家看看，乐乐就好

**Comment by sunface** [comment]
先关闭了，大家想评论可以进"老鼠出洞01“下评论
