### ISSUE TITLE
Can it support dark modes similar to Grafana?

### ISSUE THREAD

**Issue by gravese** [origin-brain/deepops#229]
Can it support dark modes similar to Grafana?

**Comment by sunface** [comment]
Hi, tripitakav, thanks for your suggestion.

Datav already support dark modes, you can click the User icon in left sidebar to change, but dashboard with background image may has its limit. 

If this does not help you, please let me know.

**Comment by sunface** [comment]
看了你的资料，也是中国人，咱们可以通过母语交流 :D

**Comment by gravese** [comment]
好的 感谢🙏
