### ISSUE TITLE
Wrong link when vertical mobile

### ISSUE THREAD

**Issue by tarilabs** [origin-brain/deepops#233]
Hi, I stumbled on your website via Google feed recommendation.

When vertical, github redirects to Tailwind CSS github repo:
![Screenshot_20230920_205642_Chrome](https://github.com/data-observe/datav/assets/1699252/2d8efb96-038f-43fc-a1ee-790ff975f998)

This doesn't happen when I use my phone horizontal:
![Screenshot_20230920_205701_Chrome](https://github.com/data-observe/datav/assets/1699252/f81403d2-556e-49ce-9bb3-d94c4b869916)

The first screenshot is taken when long pressing "GitHub" in the kebab menu
The second screenshot is taken when long pressing the github SVG icon when horizontal (not in kebab, it is directly available)

Hope this helps :)

**Comment by sunface** [comment]
Hi @tarilabs , thanks for your feedback, problem is fixed just now :)
