### ISSUE TITLE
可考虑支持分享dashboard为公开访问，面板为只读状态

### ISSUE THREAD

**Issue by zhlii** [origin-brain/deepops#309]
rt

**Comment by sunface** [comment]
你的意思是说，在 dashboard 为 team 私有的情况下，也可以以只读状态进行分享嘛？确实是个不错的主意，目前的分享还是比较基础的。

结合你的建议，我有一些思考，你看看可行不：
1. 可以给 dashboard 增加一个只读状态的控制码，通过该控制码，实现只读状态下的各种权限控制，包括 embedding 也可以使用该状态，目前 embedding 是通过 embed=true 来判断的，可以进行统一
2. 仪表盘设置 -> 通用设置 ->权限控制section里，新增配置项开关，允许用户通过只读状态访问该私有仪表盘
3. 用户访问仪表盘时依次判断:
- 若为 team member，可以直接访问，如同目前的流程
- 若仪表盘开启了只读状态访问，则访问只读状态的仪表盘
4. 分享时，给予相关提示，例如谁可以访问该仪表盘

**Comment by sunface** [comment]
@zhlii 留个微信，交流一下吧 ：） 有些 pr 的问题要沟通一下哈。。

**Comment by zhlii** [comment]
> @zhlii 留个微信，交流一下吧 ：） 有些 pr 的问题要沟通一下哈。。

微信号：coutdotfun

**Comment by yulichun** [comment]
现在为dashboard设置为all的情况下，通过dahsboard的"嵌入Embed"也是无法分享的，Embed的分享链接无法在不登陆的情况下访问。

**Comment by yulichun** [comment]
推荐dahsboard的"嵌入Embed"

**Comment by sunface** [comment]
done
