### ISSUE TITLE
无法运行datav二进制程序，报error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"

### ISSUE THREAD

**Issue by yulichun** [origin-brain/deepops#312]
hi，我在windows、linux上都尝试了直接运行release下的安装包，但都报错：

error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"

且尝试在自己的环境通过go build -o datav.exe，编译出来的二进制运行后也报该错误。

该如何解决呢？谢谢老师们指导下

**Comment by sunface** [comment]
用 CGO_ENABLED=1 试试？～～～没遇到过这个问题，后面准备搞一个 docker 的运行和开发环境，这样应该比较方便 ：D

**Comment by yulichun** [comment]
好的，我试一试

**Comment by sunface** [comment]
不过建议用 main 分支的代码来自己编译运行，release 有些老了。。。1.0release 还得一阵子 @yulichun

**Comment by yulichun** [comment]
本地安装安装mingw-w64后，使用cgo编译就能正常运行了。命令：
CGO_ENABLED=1 go build -o datav.exe
