### ISSUE TITLE
变量中使用prometheus数据源，label_values方式Metric输入框不支持大写字母

### ISSUE THREAD

**Issue by yulichun** [origin-brain/deepops#315]
![D39F558F-2BCE-4dc3-9FFA-B18F23386C3C](https://github.com/data-observe/datav/assets/28618703/7537f33b-c8f3-4f2d-b052-5d071c884bb3)

**Comment by sunface** [comment]
好，你这是 release 版本还是 main 分支

**Comment by yulichun** [comment]
是main分支哦

**Comment by sunface** [comment]
已解决 :D
