### ISSUE TITLE
创建新成员报错

### ISSUE THREAD

**Issue by yulichun** [origin-brain/deepops#320]
![207569B1-1521-406f-B36E-D62ACCD890E2](https://github.com/observe-x/observex/assets/28618703/77d91b2e-0274-484f-a368-e65e112115e3)

**Comment by sunface** [comment]
got it, thanks :)

**Comment by sunface** [comment]
测试了下，这个不是 Bug，原因是：你需要向一个 team 中添加成员，需要先在全局用户中创建该成员，可以访问 /admin/users 中添加。

不过这里的提示和流程都有问题，确实会给用户很大的误解，我优化下。

**Comment by yulichun** [comment]
ok,确实是流程上的问题，在admin用户的“个人设置/管理员面板”中可以创建新成员

**Comment by sunface** [comment]
> ok,确实是流程上的问题，在admin用户的“个人设置/管理员面板”中可以创建新成员

最新的代码中，我加了一些提示，并做了些优化
