### ISSUE TITLE
一个很严重的问题，变量中prometheus的表达式中不支持引用超过1个其他变量

### ISSUE THREAD

**Issue by yulichun** [origin-brain/deepops#325]
如图：
![22EB9759-DC4C-4690-9AB0-6EA6D878983D](https://github.com/xObserve/xObserve/assets/28618703/74c5395a-44aa-4e14-94fc-0c672894819a)
我在该变量的表达式中引用了两个其他变量，就无法通过label_values方式获取值了

**Comment by yulichun** [comment]
如上，我仅仅是引用了url和proxy_service两个变量

**Comment by sunface** [comment]
好的。。谢谢反馈，等我把新的多租户和团队系统搞定后，就解决这个问题

**Comment by sunface** [comment]
done
