### ISSUE TITLE
其他项目可以只集成仪表盘页面，目的是在页面上拖动仪表盘的图表布局，菜单等框架布局用自己项目的

### ISSUE THREAD

**Issue by yulichun** [origin-brain/deepops#326]
其他项目可以只集成仪表盘页面，目的是在页面上拖动仪表盘的图表布局，菜单等框架布局用自己项目的。
针对这样的需求，有什么建议呢？
感谢

**Comment by sunface** [comment]
你好，可以加我微信 isunface 细聊

**Comment by sunface** [comment]
1. 支持在嵌入时，只隐藏仪表盘的左侧菜单
2. 若用户为未登录状态，则需要进行登录跳转，然后再跳回当前页面
3. 通过 API Token 来授权未登录用户对仪表盘进行修改

**Comment by sunface** [comment]
Two things:
1. Allow embedding dashboard header
2. Allow login when embedding

**Comment by sunface** [comment]
One more thing : support editing dashboard with API token to avoid login action.

#351
