### ISSUE TITLE
为什么会弹出大量的这类日志呢：http://localhost:4318/v1/traces

### ISSUE THREAD

**Issue by yulichun** [origin-brain/deepops#338]
日志内容：
traces export: Post "http://localhost:4318/v1/traces": dial tcp [::1]:4318: connectex: No connection could be made because the target machine actively refused it.

**Comment by sunface** [comment]
到时候我处理下，这个日志是因为 query 服务在向 otel-collector 推送 traces 数据

**Comment by sunface** [comment]
已解决，目前默认的配置中，otlp_exporter 将被设置为空。用于需要按需开启自监控
