### ISSUE TITLE
Adapt Grafana Tempo

### ISSUE THREAD

**Issue by Cloud-Yao** [origin-brain/deepops#376]
Hi , xobserve developer, do you have plan to adapt grafana tempo , our company use grafana full stack , loki , mimir and tempo

**Comment by sunface** [comment]
你好，目前产品的定位是可观测性产品，不是可视化产品，虽然 datav 是一个独立的可视化服务。

所以至少近期是没办法支持的，但是欢迎贡献插件 :D

**Comment by Cloud-Yao** [comment]
木问题哈
