### ISSUE TITLE
关于License更新的疑问

### ISSUE THREAD

**Issue by yuboon** [origin-brain/deepops#407]
![image](https://github.com/xobserve/xo/assets/45093416/b95afb88-1493-4b8a-81d3-701986291c90)

**刚才注意到代码仓库的 License 由 apache license 2.0 更新为了 AGPL，官网的说明还未更新，License更新之前的版本还能以 apache license 2.0 使用吗**

> 最近才因为grafana许可证的原因切换过来，没想到这个License也变了  😂

**Comment by sunface** [comment]
之前的版本是可以的。你们是要用来做商业化云服务吗？如果没有的话，协议并不影响，现在很多开源都转向 AGPL3 了

**Comment by yuboon** [comment]
不做云服务，就是集成到自己的项目中，统一打包给客户使用，这种AGPL没有问题吗 ?  AGPL协议不是具有传染性么，项目代码也得开源

**Comment by sunface** [comment]
我改回去了，你们的这种场景确实会受限。

**Comment by yuboon** [comment]
👍，后面不会再改了吧 😂

**Comment by sunface** [comment]
应该不会改了，AGPL 对我来说不是必须的

**Comment by sunface** [comment]
出于长远考虑，我还是把 LICENSE 更换成 AGPL3.0。如果你需要分发可以使用之前的版本哈

**Comment by yuboon** [comment]
OK
